### ISSUE TITLE
Would the server work inside Unity?

### ISSUE THREAD

**Issue by rev111** [mul83rry/TcpServerKit#1]
Hi, I'm looking for a solution to use the same game server for single player without internet as well as a dedicated server for multiple clients.
My idea for single player is to start and connect to a local server on the device from inside a unity game. That server should not have dependencies on Unity APIs, as it should also be possible to run it on (for example) Linux on a remote machine.
Would that be possible with this project?

Thanks, rev.

**Comment by mul83rry** [comment]
hi @rev111, no this`s not supported
